### ISSUE TITLE
Its not very clear how to give permissions

### ISSUE THREAD

**Issue by WarlockTin** [YorickBM/TwerkingCrops#1]
Hi, on my shockbyte server i have this plugin installed, i can use it perfectly well and its a really great plugin. trouble is no one else on my server can use it and the permissions arent very clear. all i wnat to know is how to allow people to use the twerking crops in my server. otherwise great plugin. thank you

**Comment by AinulnPlayz** [comment]
> Hi, on my shockbyte server i have this plugin installed, i can use it perfectly well and its a really great plugin. trouble is no one else on my server can use it and the permissions arent very clear. all i wnat to know is how to allow people to use the twerking crops in my server. otherwise great plugin. thank you

I have the same issue as you WarlockTin, I just downloaded this plugin to try out and it seems only I can use it and my friends; the other players, are not able to use this plugin.

**Comment by YorickBM** [comment]
Hey, thank you very much. 

What you will need is a permission plugin. For example [luckperms](https://www.spigotmc.org/resources/luckperms.28140/). With this plugin you can give users the permissions they need. There are many tutorials on youtube how to use luckperms.
The permission to use the twerk functionality is: 'Twerk.Use'
